(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('TvSortService',TvSortService);

  /** @ngInject */
  function TvSortService($q,$http){
    var tvSortService = [];
/*    var tvs = [
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      },
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      }
    ];*/
    var menus = [
      {
        title:'频道',
        datas:[
          {
            title:'频道：',
            url:''
          },
          {
            'title':'电视剧',
            'url':'nav.tvSort',
            'type':'tv'
          },
          {
            'title':'电影',
            'url':'nav.movieSort',
            'type':'movie'
          },
          {
            'title':'综艺',
            'url':'nav.artsSort',
            'type':'art'
          },
          {
            'title':'动漫',
            'url':'nav.animationSort',
            'type':'animation'
          },
          {
            'title':'健康',
            'url':'nav.fitnessSort',
            'type':'fitness'
          },
          {
            'title':'教育',
            'url':'nav.teachSort',
            'type':'teach'
          }
        ]
      },
      {
        'title':'地区',
        'datas':[
          {
            'title':'地区：'
          },
          {
            'title':'全部',
            'area':''
          },
          {
            'title':'大陆',
            'area':'china'
          },
          {
            'title':'香港',
            'area':'hkong'
          },
          {
            'title':'韩国',
            'area':'korea'
          },
          {
            'title':'美国',
            'area':'american'
          },
          {
            'title':'英国',
            'area':'english'
          },
          {
            'title':'台湾',
            'area':'taiwan'
          },
          {
            'title':'泰国',
            'area':'thailand'
          },
          {
            'title':'新加坡',
            'area':'singapore'
          }
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：'
          },
          {
            'title':'全部',
            'tip':''
          },
          {
            'title':'武侠',
            'tip':'art'
          },
          {
            'title':'警匪',
            'tip':'cop'
          },
          {
            'title':'军事',
            'tip':'military'
          },
          {
            'title':'神话',
            'tip':'myth'
          },
          {
            'title':'科幻',
            'tip':'fiction'
          },
          {
            'title':'悬疑',
            'tip':'mystery'
          },
          {
            'title':'历史',
            'tip':'history'
          },
          {
            'title':'儿童',
            'tip':'children'
          },
          {
            'title':'农村',
            'tip':'countryside'
          },
          {
            'title':'都市',
            'tip':'city'
          },
          {
            'title':'家庭',
            'tip':'home'
          },
          {
            'title':'搞笑',
            'tip':'funny'
          },
          {
            'title':'偶像',
            'tip':'idol'
          },
          {
            'title':'言情',
            'tip':'romance'
          },
          {
            'title':'粤语',
            'tip':'cantonese'
          }
        ]
      },
      {
        'title':'时间',
        'datas':[
          {
            'title':'时间：'
          },
          {
            'title':'全部',
            'date':''
          },
          {
            'title':'2016',
            'date':'2016'
          },
          {
            'title':'2015',
            'date':'2015'
          },
          {
            'title':'2014',
            'date':'2014'
          },
          {
            'title':'2013',
            'date':'2013'
          },
          {
            'title':'2012',
            'date':'2012'
          },
          {
            'title':'2011',
            'date':'2011'
          },
          {
            'title':'00年代',
            'date':'2000'
          },
          {
            'title':'90年代',
            'date':'1990'
          },
          {
            'title':'80年代',
            'date':'1980'
          },
          {
            'title':'70年代',
            'date':'1970'
          },
          {
            'title':'更早',
            'date':'1960'
          }
        ]
      }
    ];
    tvSortService.getTvs = function(data){
    /*  var d = $q.defer();
      d.resolve({'data':tvs});
      return d.promise;*/
      return $http({
        method:"POST",
        url:"http://localhost:8080/end_tv_web/movieAction/find",
        data:data
      });
    };
    tvSortService.getMenus = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    }
    return tvSortService;
  }
})();

