(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('TvSortService',TvSortService);

  /** @ngInject */
  function TvSortService($q,$http){
    var tvSortService = [];
    var tvs = [
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      },
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      }
    ];
    var menus = [
      {
        'title':'频道',
        'datas':[
          {
            'title':'频道：',
          },
          {
            'title':'电视剧'
          },
          {
            'title':'电影'
          },
          {
            'title':'综艺'
          },
          {
            'title':'动漫'
          },
          {
            'title':'健康'
          },
          {
            'title':'教育'
          },
        ]
      },
      {
        'title':'地区',
        'datas':[
          {
            'title':'地区：',
          },
          {
            'title':'全部'
          },
          {
            'title':'大陆'
          },
          {
            'title':'香港'
          },
          {
            'title':'韩国'
          },
          {
            'title':'美国'
          },
          {
            'title':'英国'
          },
          {
            'title':'台湾'
          },
          {
            'title':'泰国'
          },
          {
            'title':'新加坡'
          }
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：',
          },
          {
            'title':'全部'
          },
          {
            'title':'武侠'
          },
          {
            'title':'警匪'
          },
          {
            'title':'军事'
          },
          {
            'title':'神话'
          },
          {
            'title':'科幻'
          },
          {
            'title':'悬疑'
          },
          {
            'title':'历史'
          },
          {
            'title':'儿童'
          },
          {
            'title':'农村'
          },
          {
            'title':'都市'
          },
          {
            'title':'家庭'
          },
          {
            'title':'搞笑'
          },
          {
            'title':'偶像'
          },
          {
            'title':'言情'
          },
          {
            'title':'粤语'
          }
        ]
      },
      {
        'title':'时间',
        'datas':[
          {
            'title':'时间：',
          },
          {
            'title':'全部'
          },
          {
            'title':'2016'
          },
          {
            'title':'2015'
          },
          {
            'title':'2014'
          },
          {
            'title':'2013'
          },
          {
            'title':'2012'
          },
          {
            'title':'2011'
          },
          {
            'title':'00年代'
          },
          {
            'title':'90年代'
          },
          {
            'title':'80年代'
          },
          {
            'title':'70年代'
          },
          {
            'title':'更早'
          },
        ]
      },
    ];
    tvSortService.getTvs = function(){
      var d = $q.defer();
      d.resolve({'data':tvs});
      return d.promise;
    };
    tvSortService.getMenus = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    }
    return tvSortService;
  }
})();

