(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('MovieSortService',MovieSortService);

  /** @ngInject */
  function MovieSortService($q,$http){
    var movieSortService = [];
    var movies = [
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      },
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      }
    ];
    var menus = [
      {
        'title':'频道',
        'datas':[
          {
            'title':'频道：'
          },
          {
            'title':'电视剧'
          },
          {
            'title':'电影'
          },
          {
            'title':'综艺'
          },
          {
            'title':'动漫'
          },
          {
            'title':'健康'
          },
          {
            'title':'教育'
          }
        ]
      },
      {
        'title':'地区',
        'datas':[
          {
            'title':'地区：'
          },
          {
            'title':'全部'
          },
          {
            'title':'大陆'
          },
          {
            'title':'香港'
          },
          {
            'title':'韩国'
          },
          {
            'title':'美国'
          },
          {
            'title':'英国'
          },
          {
            'title':'台湾'
          },
          {
            'title':'泰国'
          },
          {
            'title':'新加坡'
          }
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：'
          },
          {
            'title':'全部'
          },
          {
            'title':'武侠'
          },
          {
            'title':'警匪'
          },
          {
            'title':'犯罪'
          },
          {
            'title':'科幻'
          },
          {
            'title':'战争'
          },
          {
            'title':'恐怖'
          },
          {
            'title':'惊悚'
          },
          {
            'title':'纪录片'
          },
          {
            'title':'冒险'
          },
          {
            'title':'悬疑'
          },
          {
            'title':'历史'
          },
          {
            'title':'动作'
          },
          {
            'title':'动画'
          },
          {
            'title':'喜剧'
          },
          {
            'title':'爱情'
          },
          {
            'title':'剧情'
          },
          {
            'title':'西部'
          },
          {
            'title':'传记'
          }
        ]
      },
      {
        'title':'时间',
        'datas':[
          {
            'title':'时间：'
          },
          {
            'title':'全部'
          },
          {
            'title':'2016'
          },
          {
            'title':'2015'
          },
          {
            'title':'2014'
          },
          {
            'title':'2013'
          },
          {
            'title':'2012'
          },
          {
            'title':'2011'
          },
          {
            'title':'00年代'
          },
          {
            'title':'90年代'
          },
          {
            'title':'80年代'
          },
          {
            'title':'70年代'
          },
          {
            'title':'更早'
          },
        ]
      }
    ];
    movieSortService.getMovies = function(){
      var d = $q.defer();
      d.resolve({'data':movies});
      return d.promise;
    };
    movieSortService.getMenu = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    };
    return movieSortService;
  }
})();

