(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('ArtsSortService',ArtsSortService);

  /** @ngInject */
  function ArtsSortService($q,$http){
    var artsSortService = [];
    var arts = [
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      },
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      }
    ];
    var menus = [
      {
        'title':'频道',
        'datas':[
          {
            'title':'频道：'
          },
          {
            'title':'全部'
          },
          {
            'title':'电视剧'
          },
          {
            'title':'电影'
          },
          {
            'title':'综艺'
          },
          {
            'title':'动漫'
          },
          {
            'title':'健康'
          },
          {
            'title':'教育'
          },
        ]
      },
      {
        'title':'地区',
        'datas':[
          {
            'title':'地区：',
          },
          {
            'title':'全部'
          },
          {
            'title':'大陆'
          },
          {
            'title':'香港'
          },
          {
            'title':'韩国'
          },
          {
            'title':'美国'
          },
          {
            'title':'台湾'
          },
          {
            'title':'其他'
          }
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：',
          },
          {
            'title':'全部'
          },
          {
            'title':'脱口秀'
          },
          {
            'title':'真人秀'
          },
          {
            'title':'选秀'
          },
          {
            'title':'美食'
          },
          {
            'title':'旅游'
          },
          {
            'title':'汽车'
          },
          {
            'title':'访谈'
          },
          {
            'title':'搞笑'
          },
          {
            'title':'时尚'
          },
          {
            'title':'晚会'
          },
          {
            'title':'理财'
          },
          {
            'title':'演唱会'
          },
          {
            'title':'曲艺'
          },
          {
            'title':'益智'
          },
          {
            'title':'音乐'
          },
          {
            'title':'舞蹈'
          },
          {
            'title':'体育娱乐'
          },
          {
            'title':'游戏'
          },
          {
            'title':'生活'
          }
        ]
      },
      {
        'title':'时间',
        'datas':[
          {
            'title':'时间：',
          },
          {
            'title':'全部'
          },
          {
            'title':'2016'
          },
          {
            'title':'2015'
          },
          {
            'title':'2014'
          },
          {
            'title':'2013'
          },
          {
            'title':'2012'
          },
          {
            'title':'2011'
          },
          {
            'title':'00年代'
          },
          {
            'title':'90年代'
          },
          {
            'title':'80年代'
          },
          {
            'title':'70年代'
          },
          {
            'title':'更早'
          },
        ]
      },
    ];
    artsSortService.getArts = function(){
      var d = $q.defer();
      d.resolve({'data':arts});
      return d.promise;
    };
    artsSortService.getMenu = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    };
    return artsSortService;
  }
})();

