(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('TeachSortService',TeachSortService);

  /** @ngInject */
  function TeachSortService($q,$http){
    var teachSortService = [];

    var menus = [
      {
        'title':'频道',
        datas:[
          {
            title:'频道：',
            url:''
          },
          {
            'title':'电视剧',
            'url':'nav.tvSort',
            'type':'tv'
          },
          {
            'title':'电影',
            'url':'nav.movieSort',
            'type':'movie'
          },
          {
            'title':'综艺',
            'url':'nav.artsSort',
            'type':'art'
          },
          {
            'title':'动漫',
            'url':'nav.animationSort',
            'type':'animation'
          },
          {
            'title':'健康',
            'url':'nav.fitnessSort',
            'type':'fitness'
          },
          {
            'title':'教育',
            'url':'nav.teachSort',
            'type':'teach'
          }
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：'
          },
          {
            'title':'全部',
            'tip':''
          },
          {
            'title':'幼儿',
            'tip':'child'
          },
          {
            'title':'小学',
            'tip':'primary'
          },
          {
            'title':'初中',
            'tip':'junior'
          },
          {
            'title':'高中',
            'tip':'high'
          },
          {
            'title':'外语学习',
            'tip':'foreign'
          },
          {
            'title':'理工',
            'tip':'polytechnic'
          },
          {
            'title':'历史',
            'tip':'history'
          },
          {
            'title':'心理学',
            'tip':'psychology'
          },
          {
            'title':'经济',
            'tip':'economics'
          },
          {
            'title':'政治',
            'tip':'politics'
          },
          {
            'title':'管理学',
            'tip':'manager'
          },
          {
            'title':'计算机',
            'tip':'computer'
          },
          {
            'title':'法律',
            'tip':'law'
          },
          {
            'title':'家庭教育',
            'tip':'home'
          }
        ]
      },
      {
        'title':'出品',
        'datas':[
          {
            'title':'出品：'
          },
          {
            'title':'全部',
            'area':''
          },
          {
            'title':'TED',
            'area':'TED'
          },
          {
            'title':'耶鲁大学',
            'area':'yale'
          },
          {
            'title':'哈佛大学',
            'area':'harvard'
          },
          {
            'title':'斯坦福大学',
            'tip':'stanford'
          },
          {
            'title':'麻省理工学院',
            'tip':'massachusetts'
          },
          {
            'title':'Undacity',
            'tip':'undacity'
          },
          {
            'title':'中学网上课堂',
            'tip':'middle'
          }
        ]
      }
    ];

    teachSortService.getMenu = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    };
    return teachSortService;
  }
})();

