(function() {
  'use strict';
  /**
   * Created by Administrator on 2016/3/22.
   * auth:xzc
   */
  angular
    .module('frontTvWeb')
    .service('TeachSortService',TeachSortService);

  /** @ngInject */
  function TeachSortService($q,$http){
    var teachSortService = [];
    var teaches = [
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      },
      {
        image:'/assets/images/tv/01.jpg',
        message:'aa',
        id:1
      },
      {
        image:'/assets/images/tv/02.jpg',
        message:'aa',
        id:2
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:3
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:4
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:5
      },
      {
        image:'/assets/images/tv/06.jpg',
        message:'aa',
        id:6
      },
      {
        image:'/assets/images/tv/07.jpg',
        message:'aa',
        id:7
      },
      {
        image:'/assets/images/tv/08.jpg',
        message:'aa',
        id:8
      },
      {
        image:'/assets/images/tv/09.jpg',
        message:'aa',
        id:9
      },
      {
        image:'/assets/images/tv/05.jpg',
        message:'aa',
        id:10
      },
      {
        image:'/assets/images/tv/04.jpg',
        message:'aa',
        id:11
      },
      {
        image:'/assets/images/tv/03.jpg',
        message:'aa',
        id:12
      }
    ];
    var menus = [
      {
        'title':'频道',
        'datas':[
          {
            'title':'频道：',
          },
          {
            'title':'电视剧'
          },
          {
            'title':'电影'
          },
          {
            'title':'综艺'
          },
          {
            'title':'动漫'
          },
          {
            'title':'健康'
          },
          {
            'title':'教育'
          },
        ]
      },
      {
        'title':'类型',
        'datas':[
          {
            'title':'类型：',
          },
          {
            'title':'全部'
          },
          {
            'title':'幼儿'
          },
          {
            'title':'小学'
          },
          {
            'title':'初中'
          },
          {
            'title':'高中'
          },
          {
            'title':'外语学习'
          },
          {
            'title':'理工'
          },
          {
            'title':'历史'
          },
          {
            'title':'心理学'
          },
          {
            'title':'经济'
          },
          {
            'title':'政治'
          },
          {
            'title':'管理学'
          },
          {
            'title':'计算机'
          },
          {
            'title':'法律'
          },
          {
            'title':'家庭教育'
          }
        ]
      },
      {
        'title':'出品',
        'datas':[
          {
            'title':'出品：',
          },
          {
            'title':'TED'
          },
          {
            'title':'泰学传媒'
          },
          {
            'title':'耶鲁大学'
          },
          {
            'title':'哈佛大学'
          },
          {
            'title':'斯坦福大学'
          },
          {
            'title':'麻省理工学院'
          },
          {
            'title':'Undacity'
          },
          {
            'title':'中学网上课堂'
          }
        ]
      }
    ];
    teachSortService.getTeaches = function(){
      var d = $q.defer();
      d.resolve({'data':teaches});
      return d.promise;
    };
    teachSortService.getMenu = function(){
      var d = $q.defer();
      d.resolve({'data':menus});
      return d.promise;
    };
    return teachSortService;
  }
})();

